name: Flow Type Check

on:
  push:
    branches: 
      - main
      - master
      - develop
      - tool_test/**
  pull_request:
    branches:
      - main
      - master
      - develop
      - tool_test/**

jobs:
  flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: cp install/package.json package.json

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

        - name: NPM Install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Run Flow check
        run: npm run flow

      - name: Generate Flow report artifact
        run: npm run flow:report

      - name: Upload Flow report
        uses: actions/upload-artifact@v4
        with:
          name: flow-report
          path: flow_report.txt

